// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const rawUrl = process.env.AIVEN_DATABASE_URL || process.env.DATABASE_URL || '';

const rawUrlIncludesText = rawUrl.includes('?')
  ? `${rawUrl}&sslaccept=accept_invalid_certs`
  : `${rawUrl}?sslaccept=accept_invalid_certs`;

const rawUrlIncludes = rawUrl.includes('sslaccept=')
  ? rawUrl
  : rawUrlIncludesText;

const formattedUrl = rawUrl ? rawUrlIncludes : '';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  datasource: {
    url: formattedUrl,
  },
});
